# 基础站点信息 - 请根据实际情况修改
siteTitle: 百业  # 显示在浏览器标题栏和页面上的站点名称
siteDescription: 燕云十六声百业宣传站点 - 一个百业宣传模板,支持静态网页导出
baseUrl: https://your-deploy-url/  # 部署后的完整URL，用于SEO和分享

# 站点图标配置 - 请替换为您的图标链接
siteIcon:
  favicon: https://webinput.nie.netease.com/img/yysls/icon.png/128  # 网站图标链接 (ICO格式, 32x32px)
  icon16: https://webinput.nie.netease.com/img/yysls/icon.png/128  # 16x16px 图标
  icon32: https://webinput.nie.netease.com/img/yysls/icon.png/128  # 32x32px 图标
  appleTouchIcon: https://webinput.nie.netease.com/img/yysls/icon.png/128  # 苹果设备图标 (180x180px)

# 联系方式配置 - 根据需要填写
contactWebhook: ""  # 用于表单提交的Webhook URL（如果需要）
defaultAvatar: /assets/placeholders/avatar-small.svg  # 默认头像路径

# 社交媒体链接 - 填写实际的联系方式
socialMedia:
  QQ: ""  # QQ群或QQ号
  wechat: ""  # 微信号
  weibo: ""  # 微博地址
  email: ""  # 联系邮箱

# 申请加入相关设置
applicationSettings:
  enableApplicationForm: true  # 是否启用申请表单
  applicationEmail: ""  # 接收申请的邮箱
  expectedResponseTime: 3-7个工作日  # 预期响应时间
  applicationRequirements:  # 申请要求列表
    - 如实填写个人信息
    - 保持邮箱畅通以便联系
    - 遵守相关规定和要求
    - 接受审核流程

# SEO和页面元数据 - 优化搜索引擎表现
siteMetadata:
  keywords:  # SEO关键词
    - 燕云十六声
    - 百业
    - 游戏社区
    - 团队
  author: 百业  # 作者/创建者
  language: zh-CN  # 页面语言代码
  lastUpdated: "2024-09-21"  # 最后更新日期 - 请及时更新
  version: 0.1.0  # 站点版本号

# 页面显示设置 - 控制页面元素的显示
displaySettings:
  showMemberJoinDate: true  # 是否显示成员加入日期
  showMemberLocation: true  # 是否显示成员地理位置
  showMemberTags: true  # 是否显示成员标签
  maxMemberTagsDisplay: 3  # 最多显示的标签数量
  enableDarkMode: true  # 是否启用深色模式
  defaultTheme: light  # 默认主题：light 或 dark

# 内容警告和提醒
contentWarnings:
  showPlaceholderWarnings: true  # 是否显示占位内容警告
  showSourcesReminder: true  # 是否显示信息来源提醒
  adminNoticeEnabled: true  # 是否启用管理员通知